#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Created on Sun Jun 22 14:32:30 2025
#@author: shayneufeld


name: local-llm-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - gradio
      - langchain
      - duckduckgo-search
      - pymupdf
      - pandas
      - openai
      - tiktoken
      - chromadb
      - pyyaml
      - rich
      - pytest
      - black
      - flake8